GET http://localhost:5500/api/users HTTP/1.1
### 
GET http://localhost:5500/api/users/2 HTTP/1.1

###
POST http://localhost:5500/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzQxNjc0MzAsImV4cCI6MTczNDE2ODMzMCwic3ViIjoiOSJ9.u870OxQt9dmAN29V06nIdIlL1M0BwJFmwpWDDOMPXXDXoNbafvGXBKrZB6xBJs9H0zYBTS2EkRXnkNSjXR2xXA
content-type: application/json

{
    "name": "John Doe 4",
    "email": "johndoe4@example.com",
    "password": "password",
    "role": "EMPLOYEE"
}

### 
DELETE http://localhost:5500/api/users/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzQxNjQzMzUsImV4cCI6MTczNDE2NTIzNSwic3ViIjoiMiJ9.4G5aerMkba6NRM1SzfcECLKYGqGoTiYBUWFct1iPlpWPT2ZdPzqYjFqci-itkx7Pz_V8m3Hib7ySi3ZQJ2hgfw
### 
PATCH http://localhost:5500/api/users/2 HTTP/1.1